"""
AIVOA Prompt Registry Index
Provides semantic versioning and centralized exports for all LLM prompts.
"""

from .extraction_v1 import COMPLAINT_EXTRACTION_SYSTEM_PROMPT, PROMPT_VERSION as EXTRACTION_PROMPT_VERSION
from .edit_v1 import NATURAL_LANGUAGE_EDIT_SYSTEM_PROMPT, PROMPT_VERSION as EDIT_PROMPT_VERSION
from .risk_v1 import RISK_ASSESSMENT_SYSTEM_PROMPT, PROMPT_VERSION as RISK_PROMPT_VERSION
from .completeness_v1 import COMPLETENESS_SYSTEM_PROMPT, PROMPT_VERSION as COMPLETENESS_PROMPT_VERSION
from .summary_v1 import SUMMARY_SYSTEM_PROMPT, PROMPT_VERSION as SUMMARY_PROMPT_VERSION
from .safety_v1 import PROMPT_INJECTION_DIRECTIVE, PROMPT_VERSION as SAFETY_PROMPT_VERSION

PROMPT_VERSION = EXTRACTION_PROMPT_VERSION

PROMPT_REGISTRY = {
    "extraction": EXTRACTION_PROMPT_VERSION,
    "edit": EDIT_PROMPT_VERSION,
    "risk": RISK_PROMPT_VERSION,
    "completeness": COMPLETENESS_PROMPT_VERSION,
    "summary": SUMMARY_PROMPT_VERSION,
    "safety": SAFETY_PROMPT_VERSION
}

__all__ = [
    "COMPLAINT_EXTRACTION_SYSTEM_PROMPT",
    "NATURAL_LANGUAGE_EDIT_SYSTEM_PROMPT",
    "RISK_ASSESSMENT_SYSTEM_PROMPT",
    "COMPLETENESS_SYSTEM_PROMPT",
    "SUMMARY_SYSTEM_PROMPT",
    "PROMPT_INJECTION_DIRECTIVE",
    "PROMPT_VERSION",
    "PROMPT_REGISTRY"
]
