"""initial_schema_with_indexes_and_constraints

Revision ID: b9529d37df04
Revises: 
Create Date: 2026-08-18 02:42:10.417422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9529d37df04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_complaint_documents_complaint_id'), 'complaint_documents', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_documents_uploaded_at'), 'complaint_documents', ['uploaded_at'], unique=False)
    op.add_column('complaint_events', sa.Column('actor', sa.String(length=100), nullable=False, server_default='ai_copilot'))
    op.create_index(op.f('ix_complaint_events_complaint_id'), 'complaint_events', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_events_created_at'), 'complaint_events', ['created_at'], unique=False)
    op.create_index('ix_events_complaint_created', 'complaint_events', ['complaint_id', 'created_at'], unique=False)
    op.add_column('complaints', sa.Column('field_provenance', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_complaints_complaint_type'), 'complaints', ['complaint_type'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_created_status', 'complaints', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_customer_name'), 'complaints', ['customer_name'], unique=False)
    op.create_index('ix_complaints_product_batch', 'complaints', ['product_name', 'batch_number'], unique=False)
    op.create_index(op.f('ix_complaints_product_name'), 'complaints', ['product_name'], unique=False)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index('ix_complaints_status_severity', 'complaints', ['status', 'severity'], unique=False)
    op.create_check_constraint('ck_complaints_priority', 'complaints', "priority IN ('Low', 'Normal', 'High', 'Urgent')")
    op.create_check_constraint('ck_complaints_severity', 'complaints', "severity IN ('Low', 'Medium', 'High', 'Critical')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_complaints_severity', 'complaints', type_='check')
    op.drop_constraint('ck_complaints_priority', 'complaints', type_='check')
    op.drop_index('ix_complaints_status_severity', table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_product_name'), table_name='complaints')
    op.drop_index('ix_complaints_product_batch', table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_name'), table_name='complaints')
    op.drop_index('ix_complaints_created_status', table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_type'), table_name='complaints')
    op.drop_column('complaints', 'field_provenance')
    op.drop_index('ix_events_complaint_created', table_name='complaint_events')
    op.drop_index(op.f('ix_complaint_events_created_at'), table_name='complaint_events')
    op.drop_index(op.f('ix_complaint_events_complaint_id'), table_name='complaint_events')
    op.drop_column('complaint_events', 'actor')
    op.drop_index(op.f('ix_complaint_documents_uploaded_at'), table_name='complaint_documents')
    op.drop_index(op.f('ix_complaint_documents_complaint_id'), table_name='complaint_documents')
    # ### end Alembic commands ###
