"""
AIVOA Prompts Module Facade (Backwards compatibility)
"""
from backend.app.agents.prompts import (
    COMPLAINT_EXTRACTION_SYSTEM_PROMPT,
    NATURAL_LANGUAGE_EDIT_SYSTEM_PROMPT,
    RISK_ASSESSMENT_SYSTEM_PROMPT,
    COMPLETENESS_SYSTEM_PROMPT,
    SUMMARY_SYSTEM_PROMPT,
    PROMPT_INJECTION_DIRECTIVE,
    PROMPT_VERSION,
    PROMPT_REGISTRY
)

__all__ = [
    "COMPLAINT_EXTRACTION_SYSTEM_PROMPT",
    "NATURAL_LANGUAGE_EDIT_SYSTEM_PROMPT",
    "RISK_ASSESSMENT_SYSTEM_PROMPT",
    "COMPLETENESS_SYSTEM_PROMPT",
    "SUMMARY_SYSTEM_PROMPT",
    "PROMPT_INJECTION_DIRECTIVE",
    "PROMPT_VERSION",
    "PROMPT_REGISTRY"
]
